version: '3.9'
services:
  translation-api:
    image: "translation-api:latest"
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=postgres
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/cable/no-auth/actuator/health" ]
      interval: 3s
      timeout: 5s
      retries: 5
    volumes:
      - ./src/main/resources/db/migration:/flyway
  postgres:
    #uncomment following line for M1 users
    platform: linux/arm64/v8
    image: "postgres:16"
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=translations_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 2s
      timeout: 5s
      retries: 10
      start_period: 5s
